definitions:
  models.Items:
    properties:
      description:
        type: string
      id:
        type: integer
      itemCode:
        type: string
      order_id:
        type: integer
      quantity:
        type: integer
    type: object
  models.Order:
    properties:
      customerName:
        type: string
      id:
        type: integer
      items:
        items:
          $ref: '#/definitions/models.Items'
        type: array
      orderedAt:
        type: string
    type: object
  order.ItemResponse:
    properties:
      description:
        type: string
      itemCode:
        type: string
      quantity:
        type: integer
    type: object
  order.OrderResponse:
    properties:
      customerName:
        type: string
      id:
        type: integer
      items:
        items:
          $ref: '#/definitions/order.ItemResponse'
        type: array
      orderedAt:
        type: string
    type: object
  responses.ErrorMessage:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: aputradewantara@gmail.com
    name: Alif Dewantara
    url: http://github.com/alifdwt
  description: This is an API for Digitalent-Golang Assignment 2
  termsOfService: http://swagger.io/terms/
  title: Digitalent-Golang
  version: "1.0"
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: Get all order
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/order.OrderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorMessage'
      summary: Get all order
      tags:
      - Order
    post:
      consumes:
      - application/json
      description: Create a new order
      parameters:
      - description: Create order
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/order.OrderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorMessage'
      summary: Create order
      tags:
      - Order
  /orders/{orderId}:
    delete:
      consumes:
      - application/json
      description: Delete order
      parameters:
      - description: Order ID
        in: path
        name: orderId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorMessage'
      summary: Delete order
      tags:
      - Order
    put:
      consumes:
      - application/json
      description: Update order
      parameters:
      - description: Order ID
        in: path
        name: orderId
        required: true
        type: integer
      - description: Update order
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/order.OrderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorMessage'
      summary: Update order
      tags:
      - Order
swagger: "2.0"
